### ISSUE TITLE
Exe Won't Run

### ISSUE THREAD

**Issue by blayzec29** [Lauriethefish/QuestPatcher#144] opened 2023-12-25 19:09 UTC
I have downloaded the .exe file and it won't run i even tried the standalone still won't run idk what to do.

**Comment by ALERTua** [comment] 2023-12-26 08:22
same.

**Comment by grego31430** [comment] 2023-12-26 14:14
Same here ...
Strange things, from fresh install Soft is trying to download and stop :
![image](https://github.com/Lauriethefish/QuestPatcher/assets/22960003/a436a04d-f995-4e19-a454-5401fad98b3d)
But if I run an adb server, it stop when detect trying to get the adb version :
![image](https://github.com/Lauriethefish/QuestPatcher/assets/22960003/62a7d6c9-b139-4866-b79d-e4678ceb51c9)

I've tried to install all the .net SDK 6.0, but this not solved the issue ...

**Comment by Lauriethefish** [comment] 2023-12-27 09:52
There's no need to install the SDK for dotnet 6, the runtime is included with the app.

This issue is a duplicate of (link), essentially the app crashes without triggering the unhandled exception handler, (which shouldn't be possible) so there's no logging to explain what went wrong. I have some evidence to suggest it relates to the avalonia update qp recently underwent.

It doesn't relate to the startup process or anything, as it occurs at a random point during startup, typically when the window is clicked, but not always. I can't reproduce it at the moment but I'm doing all I can.

**Comment by ALERTua** [comment] 2023-12-27 12:53
> There is some suggestion that running as administrator fixes the issue.

It does! Thank you!

**Comment by Lauriethefish** [comment] 2023-12-27 13:16
closing due to being a duplicate

**Closed by Lauriethefish** 2023-12-27 13:16 UTC
