### ISSUE TITLE
Quest Patcher To Many Devices is there a Fix?

### ISSUE THREAD

**Issue by MrMukky** [Lauriethefish/QuestPatcher#65] opened 2022-03-07 20:31 UTC
@Lauriethefish Is there a fix to this bug because im trying get the app working for when mods come back out!?

**Comment by Lauriethefish** [comment] 2022-03-08 06:12
It's not a bug, you need to remove any emulators that you currently have running. This issues section is for bugs only, so I'm gonna have to close this,

**Closed by Lauriethefish** 2022-03-08 06:12 UTC

**Comment by XboxGitHub** [comment] 2022-09-10 00:08
![Screenshot (157)](https://user-images.githubusercontent.com/67390048/189460622-960688d2-a28b-4e75-9a60-0c60908a7c97.png)
Why does it say that when I try to activate computer mods

**Comment by XboxGitHub** [comment] 2022-09-10 00:09
and it's always a beat saber mod, when i delete it, it just keeps popping up in the files
