### ISSUE TITLE
QuestPatcher (mac) 

### ISSUE THREAD

**Issue by RuggyVR** [Lauriethefish/QuestPatcher#91] opened 2022-09-04 15:27 UTC
Hello, Today I decided to start modding the gorilla tag on my mac, but then it said questpatcher is damaged when I opened it. If someone could look into this issue I would appreciate it.

**Comment by Lauriethefish** [comment] 2022-09-12 09:24
Duplicate of #49

**Closed by Lauriethefish** 2022-09-12 09:24 UTC
