### ISSUE TITLE
questpatcher brokey brokey

### ISSUE THREAD

**Issue by NattoTheGreat** [Lauriethefish/QuestPatcher#33] opened 2021-09-11 03:24 UTC
i went to go laucnh gorilla tag and it kept on saying "gorilla tag has stopped"
so i uninstalled it and re installed it and realized all my mods were gone
so i went to go launch quest patcher and it keeps on having an error at startup
and it keeps on closing

QuestPatcher.Core.AdbException: mkdir: '/sdcard/QuestPatcher': No such file or directory

   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 148
   at QuestPatcher.Core.AndroidDebugBridge.RunShellCommands(List`1 commands) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 275
   at QuestPatcher.Core.AndroidDebugBridge.CreateDirectories(List`1 paths) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 310
   at QuestPatcher.Core.Modding.ModManager.CreateModsDirectories() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Modding\ModManager.cs:line 103
   at QuestPatcher.Core.Modding.ModManager.DetectAndRemoveOldMods() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Modding\ModManager.cs:line 119
   at QuestPatcher.Core.QuestPatcherService.MigrateOldFiles() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 170
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 127
   at QuestPatcher.Services.QuestPatcherUIService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUIService.cs:line 89

**Comment by Lauriethefish** [comment] 2021-09-12 14:31
This is unlikely to be an issue with QuestPatcher, and is more likely to be a bug with one of your mods crashing the game. To fix the opening issue however, delete `/sdcard/QuestPatcher` using the SideQuest file manager.

Closing due to inability to reproduce second issue, and the first not being QuestPatcher related.

**Closed** 2021-09-12 14:31 UTC

**Comment by soulessnight4** [comment] 2021-11-10 06:22
ive been trying to download mods for gorilla tag for a while now and today after getting lib files that contain codegen and monkecomputer but each time i try to open the file for questpatcher it just says that my quest is offline

**Comment by Lauriethefish** [comment] 2021-11-10 06:34
This thread is not for support.

**Comment by soulessnight4** [comment] 2021-11-10 06:36
then where do i go

**Comment by Lauriethefish** [comment] 2021-11-10 06:40
Nowhere, gorilla tag quest mods are not available at the moment.
