### ISSUE TITLE
Fail to Patch on QP v2.8.0 on macOS 14.0

### ISSUE THREAD

**Issue by hjstn** [Lauriethefish/QuestPatcher#168] opened 2024-04-04 03:15 UTC
It seems like QuestPatcher is unable to read the JSON at `https://raw.githubusercontent.com/Lauriethefish/QuestUnstrippedUnity/main/index.json`, which seems weird, given that it is able to download `platform-tools` and other dependencies just fine. I can open the link in a browser and load it correctly, and CURLing it on a terminal also works, so it doesn't seem to be an internet issue. I'm not running any VPNs.

User logs excerpt
```
Downloading files . . .
Downloading "libmainloader.so"
Downloaded "libmainloader.so"
Downloading "libsl2.so"
Downloaded "libsl2.so"
Uploading scotland2 to the quest
Patching failed!
```

Logs excerpt
```
[2024-04-04 10:53:36 VRB] Ran Chmod on /sdcard/ModData/com.beatgames.beatsaber/Modloader/libsl2.so with +r
[2024-04-04 10:53:36 DBG] Executing ADB command: adb shell "chmod +r '/sdcard/ModData/com.beatgames.beatsaber/Modloader/libsl2.so'"
[2024-04-04 10:53:36 DBG] Downloading libunity index for the first time . . .
[2024-04-04 10:55:16 ERR] Patching failed!
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at QuestPatcher.Core.Patching.PatchingManager.GetUnstrippedUnityPath() in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher.Core/Patching/PatchingManager.cs:line 90
   at QuestPatcher.Core.Patching.PatchingManager.PatchApp() in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher.Core/Patching/PatchingManager.cs:line 632
   at QuestPatcher.ViewModels.PatchingViewModel.StartPatching() in /Users/runner/work/QuestPatcher/QuestPatcher/QuestPatcher/ViewModels/PatchingViewModel.cs:line 61
```

**Comment by Lauriethefish** [comment] 2024-08-17 21:22
Gonna close this as it was probably caused by a temporary GitHub outage or another network issue

**Closed by Lauriethefish** 2024-08-17 21:22 UTC
