### ISSUE TITLE
Crash on start on mac

### ISSUE THREAD

**Issue by hiwhdge** [Lauriethefish/QuestPatcher#88] opened 2022-08-21 11:55 UTC
i keep trying to open quest patcher and it says its damaged and cant be opened

**Comment by Lauriethefish** [comment] 2022-08-21 12:12
What model of mac do you have?

**Comment by hiwhdge** [comment] 2022-08-21 12:22
macos catalina

**Comment by Lauriethefish** [comment] 2022-08-21 12:23
No, not your OS. What mac do you have?

**Comment by hiwhdge** [comment] 2022-08-21 12:23
trying to find where it says that

**Comment by hiwhdge** [comment] 2022-08-21 12:30
Imac 21.5-inch late 2013

**Comment by Lauriethefish** [comment] 2022-09-12 09:24
Duplicate of #49

**Closed by Lauriethefish** 2022-09-12 09:24 UTC
