### ISSUE TITLE
Unhandled Load Error

### ISSUE THREAD

**Issue by reallycoo1** [Lauriethefish/QuestPatcher#157] opened 2024-02-27 22:27 UTC
Hello you lovely lot,

(I'm trying to get to mod beat sabre)

I've looked at previous posts, and have tried restating, opening QP as administrator, but I keep getting this:

QuestPatcher.Core.AdbException: chmod: chmod '/sdcard/Android/data/com.beatgames.beatsaber/files/mods/' to 0777: Operation not permitted

   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 149
   at QuestPatcher.Core.AndroidDebugBridge.RunShellCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 187
   at QuestPatcher.Core.AndroidDebugBridge.RunShellCommands(List`1 commands) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 174
   at QuestPatcher.Core.AndroidDebugBridge.Chmod(List`1 paths, String permissions) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 319
   at QuestPatcher.Core.Modding.ModManager.CreateModDirectories() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Modding\ModManager.cs:line 117
   at QuestPatcher.Core.Modding.ModManager.LoadModsForCurrentApp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Modding\ModManager.cs:line 123
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 129
   at QuestPatcher.Services.QuestPatcherUiService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 91

When I click on "Change App" it's already on Beat Sabre, then it just shuts down QP?

The moment I get to play "Trees" by 21 Pilots will be everything.

I still live in hope.

Any help, much appreciated.

**Comment by justix123** [comment] 2024-04-08 13:39
hey i am also getting the unhandled load error but idk why. hopefully someone comes and helps us both. but if i do manage to fix this problem i will help u.

**Comment by vMamr** [comment] 2024-04-08 16:58
QuestPatcher.Core.AdbException: Code 1: rm: chmod '/sdcard/Android/data/com.beatgames.beatsaber/files/mods/' to 0700: Operation not permitted
rm: /sdcard/Android/data/com.beatgames.beatsaber/files/mods/: Permission denied
   at QuestPatcher.Core.AndroidDebugBridge.RunCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 433
   at QuestPatcher.Core.AndroidDebugBridge.RunShellCommand(String command, Int32[] allowedExitCodes) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 466
   at QuestPatcher.Core.AndroidDebugBridge.RemoveDirectory(String path) in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\AndroidDebugBridge.cs:line 570
   at QuestPatcher.Core.Modding.ModManager.CreateModDirectories() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Modding\ModManager.cs:line 189
   at QuestPatcher.Core.Modding.ModManager.LoadModsForCurrentApp() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\Modding\ModManager.cs:line 210
   at QuestPatcher.Core.QuestPatcherService.RunStartup() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher.Core\QuestPatcherService.cs:line 137
   at QuestPatcher.Services.QuestPatcherUiService.LoadAndHandleErrors() in D:\a\QuestPatcher\QuestPatcher\QuestPatcher\Services\QuestPatcherUiService.cs:line 96

**Comment by Lauriethefish** [comment] 2024-08-18 05:56
Duplicate of #184

**Closed by Lauriethefish** 2024-08-18 05:56 UTC
