### ISSUE TITLE
Quest Patcher not loading beacuse it cannot detect the apk 'correctly' (32 / 64 bit)

### ISSUE THREAD

**Issue by EREgoat** [Lauriethefish/QuestPatcher#190] opened 2024-08-03 00:37 UTC
![image_2024-08-02_172749074](https://github.com/user-attachments/assets/76a42159-6490-4c3a-8a9e-8536920ef705)

Quest Patcher wont finish launching and I'm getting this error message

**Comment by EREgoat** [comment] 2024-08-03 00:44
managed to turn on display logs :
![Screenshot (5)](https://github.com/user-attachments/assets/42806d64-272e-45f9-9739-cf0e2b8d4d42)

**Comment by Lauriethefish** [comment] 2024-08-10 16:11
What app are you attempting to mod?

**Comment by EREgoat** [comment] 2024-08-10 20:31
Sorry, out of town

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Lauriethefish** [comment] 2024-08-18 05:20
Bump, what app are you attempting to mod?

**Comment by EREgoat** [comment] 2024-08-27 03:46
Sorry for the delay, I was using YouTube and the process was over complicated. I found ModsBeforeFriday via a Reddit string and got the process done in ~10 min.

**Comment by EREgoat** [comment] 2024-08-27 03:54
I was trying to mod beat saber and after correctly opening Quest Pacher I accidentally closed the program. Thus resulting in a half moded beat saber that was undetected by Quest Pacher.

**Comment by Lauriethefish** [comment] 2024-09-17 10:40
Hmm, okay. I'm not sure I'll be able to reproduce this issue so I'll close it.
QuestPatcher should never produce a partially modded APK because the APK isn't installed until it's fully patched. Not sure how you got this to happen.

**Closed by Lauriethefish** 2024-09-17 10:40 UTC
