### ISSUE TITLE
multiple devices

### ISSUE THREAD

**Issue by lols5656** [Lauriethefish/QuestPatcher#98] opened 2022-11-25 16:52 UTC
I don't own blues stacks or android devices and its saying there's multiple plugged in
![Screenshot (14)](https://user-images.githubusercontent.com/119068945/204028738-4a2ec413-a9ed-489a-ae62-9b93ee355b58.png)

**Comment by Lauriethefish** [comment] 2022-11-27 21:40
If you previously had an emulator installed, chances are there might still be some trace of it left. I suggest looking up how to fully uninstall your emulator.

This issue will now be closed as it is an issue with your sideloading setup; not a bug with QuestPatcher.

**Closed by Lauriethefish** 2022-11-27 21:40 UTC
