### ISSUE TITLE
Opening, then, closing

### ISSUE THREAD

**Issue by firminunderscore** [Lauriethefish/QuestPatcher#192] opened 2024-08-10 15:31 UTC
Hey there,
I recently reinstalled Windows and now, when I want to use quest patcher, it opens, loads a bit, then closes.
I there any way to patch this ? I can't find the source of the problem.

**Comment by Lauriethefish** [comment] 2024-08-10 16:11
Duplicate of #137, see that thread for details.

**Closed by Lauriethefish** 2024-08-10 16:11 UTC
